[package]
name = "sundials"
version = "0.0.1"
edition = "2021"
authors = ["Christophe Troestler <christophe.troestler@umons.ac.be>"]
description = "One dimensional root finding algorithms"
homepage = "https://github.com/Chris00/rust-sundials"
repository = "https://github.com/Chris00/rust-sundials"
documentation = "https://docs.rs/sundials"
license = "GPL-2.0-or-later"
keywords = ["ODE", "math", "numerics", "simulation", "science"]
categories = ["mathematics", "science"]

[build-dependencies]
sundials-sys = { version = "0.2.3", git = "https://github.com/Chris00/sundials-sys.git" }

[dependencies]
sundials-sys = { version = "0.2.3", git = "https://github.com/Chris00/sundials-sys.git" }

[dev-dependencies]
eyre = "0.6.8"
