name: Cargo Build & Test
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: [stable, beta, nightly, linux32, macos, aarch64-ios, win64, windows-latest]
        include:
          - build: stable
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-gnu
          - build: beta
            os: ubuntu-latest
            rust: beta
            target: x86_64-unknown-linux-gnu
          - build: nightly
            os: ubuntu-latest
            rust: nightly
            target: x86_64-unknown-linux-gnu
          - build: linux32
            os: ubuntu-latest
            rust: stable
            target: i686-unknown-linux-gnu
          - build: macos
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
          - build: aarch64-ios
            os: macos-latest
            rust: stable
            target: aarch64-apple-ios
          - build: windows-aarch64
            os: windows-latest
            rust: stable
            target: aarch64-pc-windows-msvc
          - build: win64
            os: windows-latest
            rust: stable
            target: x86_64-pc-windows-msvc
          - build: windows-latest
            os: windows-latest
            rust: stable-x86_64
            target: x86_64-pc-windows-msvc
    steps:
    - uses: actions/checkout@master
    - run: git submodule init
    - run: git submodule update
    - name: Install Ubuntu packages
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get -y install libsundials-dev
    - name: Set up vcpkg on Windows
      if: startsWith(matrix.os, 'windows')
      run: |
        git clone https://github.com/microsoft/vcpkg
        & .\vcpkg\bootstrap-vcpkg.bat
        & .\vcpkg\vcpkg install sundials:x64-windows
    - name: Install MacOS packages (brew)
      if: startsWith(matrix.os, 'macos')
      run: brew install sundials
    - name: Install Rust (rustup)
      run: rustup update ${{ matrix.rust }} --no-self-update && rustup default ${{ matrix.rust }}
      shell: bash
    - run: rustup target add ${{ matrix.target }}
    - run: cargo build --verbose
    # - run: cargo test --verbose
    - run: cargo run --example basic
